### ISSUE TITLE
Creepereggs not working 

### ISSUE THREAD

**Issue by DeadxModz** [Indyuce/premium-creeper-eggs#1]
ERROR LOG BELOW

**Comment by DeadxModz** [comment]
> [12:49:42 WARN]: java.lang.IllegalAccessException: Class net.Indyuce.creepereggs.api.CreeperEgg can not access a member of class net.minecraft.server.v1_8_R3.EntityCreeper with modifiers "private"
> [12:49:42 WARN]: at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
> [12:49:42 WARN]: at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
> [12:49:42 WARN]: at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
> [12:49:42 WARN]: at java.lang.reflect.Field.setInt(Field.java:946)
> [12:49:42 WARN]: at net.Indyuce.creepereggs.api.CreeperEgg.explodeCreeper(CreeperEgg.java:156)
> [12:49:42 WARN]: at net.Indyuce.creepereggs.api.CreeperEgg$1.run(CreeperEgg.java:123)
> [12:49:42 WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
> [12:49:42 WARN]: at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349)
> [12:49:42 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:785)
> [12:49:42 WARN]: at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
> [12:49:42 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715)
> [12:49:42 WARN]: at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618)
> [12:49:42 WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by Indyuce** [comment]
Please specify how I can reproduce the issue

**Comment by Alekhedjran** [comment]
When is there going to be an update for 1.15.2? is their already one? PM me

**Comment by Indyuce** [comment]
I've published a build for 1.15+ on December 24th
